# Generated by Django 5.2.4 on 2025-07-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_file',
            field=models.FileField(blank=True, null=True, upload_to='course_files/'),
        ),
    ]
